cat >  ~/vsphere/install-config.yaml <<EOF
apiVersion: v1
baseDomain: osauer.local 
compute: 
- hyperthreading: Enabled 
  name: worker
  replicas: 3
  platform:
    vsphere: 
      cpus: 2
      coresPerSocket: 2
      memoryMB: 8196
      osDisk:
        diskSizeGB: 50
controlPlane: 
  hyperthreading: Enabled 
  name: master
  replicas: 3
  platform:
    vsphere: 
      cpus: 4
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 50
metadata:
  name: ocp 
networking:
  networkType: ncp 
  clusterNetwork:
  - cidr: 10.2.0.0/16
    hostPrefix: 23
  machineCIDR: 10.4.1.0/24 
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    vcenter: vcsa2.osauer.local
    username: administrator@osauer.local
    password: "SAuer1357V!"
    datacenter: PKS-DC
    defaultDatastore: datastore5
    folder: /PKS-DC/vm/ocp
    network: ms_t1_int
    apiVIP: 10.4.1.6
    ingressVIP: 10.4.1.5
    Cluster: MGMT
fips: false
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2Fzc2F1ZXIxa2d5Z216Y2Z3b3hoYTd5eWJ4bWpwZ3BlOWU6M1owVTFINVhFQllSQjNKUVZWOFJSMklWMkJEV0ROSDhNQ01YTE42TVg5MlE0UEYyWjFTTTBBTlhIWjk0Sk5SNA==","email":"sauera@vmware.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2Fzc2F1ZXIxa2d5Z216Y2Z3b3hoYTd5eWJ4bWpwZ3BlOWU6M1owVTFINVhFQllSQjNKUVZWOFJSMklWMkJEV0ROSDhNQ01YTE42TVg5MlE0UEYyWjFTTTBBTlhIWjk0Sk5SNA==","email":"sauera@vmware.com"},"registry.connect.redhat.com":{"auth":"ODEzNTkzNHx1aGMtMUtHWWdtekNGd094SGE3eVlCWE1qcEdQZTllOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lKalpXTTRZak01TURnek9EYzBNbVJsT1Roa1lXTTVZamRqWlRBNU1Ea3lOaUo5Lm9VSlhaZm4zSXUzQlgwdTRyMENiaXZzSWs3ZHlzUjJ6OUt1OUhzejZlUTlsSVU4Tm0wQXZDUzF2T2YxeUVkYTJLRHhzRmdMdkR1d0J0V3ZsdVB0dXNDVnZvSTQtcHlNVndCSlFiRUxTYTZmOWQ2VmVId0czQnNKLVprWVVMVVYtMUxWcDlidm1NWUFqMjloRFc2OEdRc1pwNVMzTzJzdlhRQ29wZTd0Ukx6TTFUd25sQW5DZHB6SUU1YWdpZEx3bEVOc3Boa182ZUFxNDJDUVZqWkJyaDY5TUE1WWNDVWpOaEdsREdnTHNPZ2tkQmRBOWZkQWtkWlByN0YwU2d2LWVpb1NVTWc4NktVb1dEUm40NXF2ZDgtYzZZWEp1d2xyVGxKbC0xWDlTem5BX0k3WC1Ia29ZaGhEUWJkN2hrb0J3dGZTcDl2RURULVhXMHgwcFFTbGR3VFRucW1OOEhHYzc1ajN4a3JwNEtvQnNpTURJZzM2ZTk0bnl0eTI2eUdRMXY3dE9MYmpNdG9ncXB3R25nVFNHazJ5dmlKNkktcU1iOVZsUV9XZlVUVFA4WWRQQ3MxamxydUhkNXJOZloxcVhjUjR0SGI3bmdUblBFN2F6ZklpM0FBaGwyckZWR3IyRkFIS0xRRGJJTkYyX0Q2OWZ0VkxvUWM1cUlfeEpGMW9SVmViNzh2V203TjY4NWdCTXE5Q1RfSkVURmpjcmRBSVRJVU1ZM3JfdHJuaG9FcG5FVU5VMWZmNVJERjFTZEZTNXVrMEkwQnk3ZWJKTy0zU2ludl9KQUEyWDdZSFEtV1lxUHdkWE5idWdKNk83a0EyeDRRaUE2UWFpbHU2TjdUN1RsUm1qNGNNbHVZYjRBMVF1YWY3eGllNm9Zc1czbEJ4eXNSTXFBazF4ZXlZ","email":"sauera@vmware.com"},"registry.redhat.io":{"auth":"ODEzNTkzNHx1aGMtMUtHWWdtekNGd094SGE3eVlCWE1qcEdQZTllOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lKalpXTTRZak01TURnek9EYzBNbVJsT1Roa1lXTTVZamRqWlRBNU1Ea3lOaUo5Lm9VSlhaZm4zSXUzQlgwdTRyMENiaXZzSWs3ZHlzUjJ6OUt1OUhzejZlUTlsSVU4Tm0wQXZDUzF2T2YxeUVkYTJLRHhzRmdMdkR1d0J0V3ZsdVB0dXNDVnZvSTQtcHlNVndCSlFiRUxTYTZmOWQ2VmVId0czQnNKLVprWVVMVVYtMUxWcDlidm1NWUFqMjloRFc2OEdRc1pwNVMzTzJzdlhRQ29wZTd0Ukx6TTFUd25sQW5DZHB6SUU1YWdpZEx3bEVOc3Boa182ZUFxNDJDUVZqWkJyaDY5TUE1WWNDVWpOaEdsREdnTHNPZ2tkQmRBOWZkQWtkWlByN0YwU2d2LWVpb1NVTWc4NktVb1dEUm40NXF2ZDgtYzZZWEp1d2xyVGxKbC0xWDlTem5BX0k3WC1Ia29ZaGhEUWJkN2hrb0J3dGZTcDl2RURULVhXMHgwcFFTbGR3VFRucW1OOEhHYzc1ajN4a3JwNEtvQnNpTURJZzM2ZTk0bnl0eTI2eUdRMXY3dE9MYmpNdG9ncXB3R25nVFNHazJ5dmlKNkktcU1iOVZsUV9XZlVUVFA4WWRQQ3MxamxydUhkNXJOZloxcVhjUjR0SGI3bmdUblBFN2F6ZklpM0FBaGwyckZWR3IyRkFIS0xRRGJJTkYyX0Q2OWZ0VkxvUWM1cUlfeEpGMW9SVmViNzh2V203TjY4NWdCTXE5Q1RfSkVURmpjcmRBSVRJVU1ZM3JfdHJuaG9FcG5FVU5VMWZmNVJERjFTZEZTNXVrMEkwQnk3ZWJKTy0zU2ludl9KQUEyWDdZSFEtV1lxUHdkWE5idWdKNk83a0EyeDRRaUE2UWFpbHU2TjdUN1RsUm1qNGNNbHVZYjRBMVF1YWY3eGllNm9Zc1czbEJ4eXNSTXFBazF4ZXlZ","email":"sauera@vmware.com"}}}' 
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDDAmgTZy5lBYo+RH4asI4QssfoCjhBIL9PfsrF9uEaPFa4cZ44qwWXA28WzriTAkxEZEYJnPpOZ414tHwRNSuq7HGIumYBnXeHUoJ4yJ6kbWu8sEfg5Cg6SPBrS/6jo4cmm4RzPMpM3crU8JKpQPwraG5hAvJjOsoxQwjqur33wdP+9OJ5up3Hitf0Wu5p/o+6veNrubdHhbYoVAsjc8i/0DpO1ex9yqfMUPkIoMvK2ydd7yvFFNiyQ+TmP+iUAEY+VMci8tqkrSe6rQzLqsA1JhtR2yPEkHOpZomy6MKSkb+JckDFl9ru7gQyKJJpP7bubD7gREqDFpwBVQk5TQJB0tIYpccMhkr7f+2Ju956kfGZ7ssKpwzsitSKBy10eVdYz7FWaZkOWdm6hnC203FefT+wKnAxweksUTWf40UHhC9kRky8psaN5/MFk3xwV1LZlX0/EjQyYuL7MdvngqFiEIi1rLBVWEUSPAoeLIuf0Lp2RlWo5EcIxOS6er+Kymgq1o26faZt+WWjVVYMJ6DuhwaV83l7arvQ7ha5XXWgQ8cacINAaDCBPSH+nK+T5KZhXwUoQaMqKKhXQyHvwI7f2gwQwGfQo//HM1/YXI4PXQmVn22+nFSxiG9ouPkxRxoU88gp4pTQmzkBM4hK20mE92Zh19ke3CwFGofyj4uPEw== root@sauer-virtual-machine'
EOF
