apiVersion: v1
baseDomain: osauer.local
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 2
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 1
metadata:
  name: ocp
networking:
  networkType: ncp
  clusterNetwork:
  - cidr: 10.128.0.0/16
    hostPrefix: 23
  machineCIDR: 10.4.3.0/24
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    vcenter: vcsa.osauer.local
    username: administrator@osauer.local
    password: SAuer1357V!
    datacenter: PKS-DC
    defaultDatastore: datastore5
pullSecret: '{"auths":{"cloud.open....)
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDb0u/puYXuWy+WwRC2AQoAnbHNfTqdada48agcImM9ZE93oC3p1Qn01xzBq8OmGlMgqg9XUZm2qLbU7qQLFAtNhP57oaSBFN3rFqPnFbyKa/GHacTZBzwiYlflP5jODQ6jhV6vplLYCFZdhW+8VLMveNsR0ro3UUzI6jgsveFd+jV/0O8euw7vmm6XEcICEzoNAnRr5x6Ih8MJjpgUR7lperQhJYsBjLTYKrI+l6QY0bvVxs5wUq/VmA1p8f8l85Wou4zocaQLHmTq/hDb2Tj45azpQTQENZiS9LuIF2DwYtrEQiiWiwS9X7vOXChodRK/ypVSR9XPD1XVbTnkNdID1dG0XyOOzTFlDTIT3rnVMs2ze08urPYLi/aWtG3ULoE5B3U3gf5efrUnLGnZofA8IvCBSdaooF1azTkCnl2BCG4kgbcmd94sshlWxSvgKIj1WNWD0CfJmAUiqWWZqCoh/OSzziO3wZlqQ5tTTbimJpQx5hIHNXw7i85gLPVw0nv7+leMAshkH3gTi3ffaBVf5wOo+F86K0DrFcl3JJBKuE3NLv9m0pyoP2eX6Q+2qodBq7uQujeWtZHR3oAAAGVi2xEyQiXt5AdzKzlWr8naQOHNGYtnwVXGG9qjZw22giMIpbeWZiqIhfM3IVOxYDalZTbVS0Iu8pAYh0UvGFRSLJ5R7Q== root@sauer-virtual-machine
