apiVersion: v1
baseDomain: osauer.local
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 0
  platform:
    vsphere:
      osDisk:
        diskSizeGB: 40
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3 
  platform:
    vsphere:
      osDisk:
        diskSizeGB: 50
metadata:
  creationTimestamp: null
  name: ocp
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.4.1.0/24
  networkType: ncp
  serviceNetwork:
  - 172.20.0.0/16
platform:
  vsphere:
    apiVIP: 10.4.1.5
    cluster: MGMT
    datacenter: PKS-DC
    defaultDatastore: datastore5
    ingressVIP: 10.4.1.6
    network: ms_t1_int
    password: SAuer1357V!
    username: administrator@osauer.local
    vCenter: vcsa.osauer.local
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNdsadoaWZ0LXJlbGVhc2UtZGV2Kdada2Fzc2F1ZXIxa2d5Z216Y2Z3b3hoYTd5eWJ4bWpwZ3BlOWU6M1owVTFINVhFQllSQjNKUVZWOFJSMklWMkJEV0ROSDhNQ01YTE42TVg5MlE0UEYyWjFTTTBBTlhIWjk0Sk5SNA==","email":"sauera@vmware.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2Fzc2F1ZXIxa2d5Z216Y2Z3b3hoYTd5eWJ4bWpwZ3BlOWU6M1owVTFINVhFQllSQjNKUVZWOFJSMklWMkJEV0ROSDhNQ01YTE42TVg5MlE0UEYyWjFTTTBBTlhIWjk0Sk5SNA==","email":"sauera@vmware.com"},"registry.connect.redhat.com":{"auth":"ODEzNTkzNHx1aGMtMUtHWWdtekNGd094SGE3eVlCWE1qcEdQZTllOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lKalpXTTRZak01TURnek9EYzBNbVJsT1Roa1lXTTVZamRqWlRBNU1Ea3lOaUo5Lm9VSlhaZm4zSXUzQlgwdTRyMENiaXZzSWs3ZHlzUjJ6OUt1OUhzejZlUTlsSVU4Tm0wQXZDUzF2T2YxeUVkYTJLRHhzRmdMdkR1d0J0V3ZsdVB0dXNDVnZvSTQtcHlNVndCSlFiRUxTYTZmOWQ2VmVId0czQnNKLVprWVVMVVYtMUxWcDlidm1NWUFqMjloRFc2OEdRc1pwNVMzTzJzdlhRQ29wZTd0Ukx6TTFUd25sQW5DZHB6SUU1YWdpZEx3bEVOc3Boa182ZUFxNDJDUVZqWkJyaDY5TUE1WWNDVWpOaEdsREdnTHNPZ2tkQmRBOWZkQWtkWlByN0YwU2d2LWVpb1NVTWc4NktVb1dEUm40NXF2ZDgtYzZZWEp1d2xyVGxKbC0xWDlTem5BX0k3WC1Ia29ZaGhEUWJkN2hrb0J3dGZTcDl2RURULVhXMHgwcFFTbGR3VFRucW1OOEhHYzc1ajN4a3JwNEtvQnNpTURJZzM2ZTk0bnl0eTI2eUdRMXY3dE9MYmpNdG9ncXB3R25nVFNHazJ5dmlKNkktcU1iOVZsUV9XZlVUVFA4WWRQQ3MxamxydUhkNXJOZloxcVhjUjR0SGI3bmdUblBFN2F6ZklpM0FBaGwyckZWR3IyRkFIS0xRRGJJTkYyX0Q2OWZ0VkxvUWM1cUlfeEpGMW9SVmViNzh2V203TjY4NWdCTXE5Q1RfSkVURmpjcmRBSVRJVU1ZM3JfdHJuaG9FcG5FVU5VMWZmNVJERjFTZEZTNXVrMEkwQnk3ZWJKTy0zU2ludl9KQUEyWDdZSFEtV1lxUHdkWE5idWdKNk83a0EyeDRRaUE2UWFpbHU2TjdUN1RsUm1qNGNNbHVZYjRBMVF1YWY3eGllNm9Zc1czbEJ4eXNSTXFBazF4ZXlZ","email":"sauera@vmware.com"},"registry.redhat.io":{"auth":"ODEzNTkzNHx1aGMtMUtHWWdtekNGd094SGE3eVlCWE1qcEdQZTllOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lKalpXTTRZak01TURnek9EYzBNbVJsT1Roa1lXTTVZamRqWlRBNU1Ea3lOaUo5Lm9VSlhaZm4zSXUzQlgwdTRyMENiaXZzSWs3ZHlzUjJ6OUt1OUhzejZlUTlsSVU4Tm0wQXZDUzF2T2YxeUVkYTJLRHhzRmdMdkR1d0J0V3ZsdVB0dXNDVnZvSTQtcHlNVndCSlFiRUxTYTZmOWQ2VmVId0czQnNKLVprWVVMVVYtMUxWcDlidm1NWUFqMjloRFc2OEdRc1pwNVMzTzJzdlhRQ29wZTd0Ukx6TTFUd25sQW5DZHB6SUU1YWdpZEx3bEVOc3Boa182ZUFxNDJDUVZqWkJyaDY5TUE1WWNDVWpOaEdsREdnTHNPZ2tkQmRBOWZkQWtkWlByN0YwU2d2LWVpb1NVTWc4NktVb1dEUm40NXF2ZDgtYzZZWEp1d2xyVGxKbC0xWDlTem5BX0k3WC1Ia29ZaGhEUWJkN2hrb0J3dGZTcDl2RURULVhXMHgwcFFTbGR3VFRucW1OOEhHYzc1ajN4a3JwNEtvQnNpTURJZzM2ZTk0bnl0eTI2eUdRMXY3dE9MYmpNdG9ncXB3R25nVFNHazJ5dmlKNkktcU1iOVZsUV9XZlVUVFA4WWRQQ3MxamxydUhkNXJOZloxcVhjUjR0SGI3bmdUblBFN2F6ZklpM0FBaGwyckZWR3IyRkFIS0xRRGJJTkYyX0Q2OWZ0VkxvUWM1cUlfeEpGMW9SVmViNzh2V203TjY4NWdCTXE5Q1RfSkVURmpjcmRBSVRJVU1ZM3JfdHJuaG9FcG5FVU5VMWZmNVJERjFTZEZTNXVrMEkwQnk3ZWJKTy0zU2ludl9KQUEyWDdZSFEtV1lxUHdkWE5idWdKNk83a0EyeDRRaUE2UWFpbHU2TjdUN1RsUm1qNGNNbHVZYjRBMVF1YWY3eGllNm9Zc1czbEJ4eXNSTXFBazF4ZXlZ","email":"sauera@vmware.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDb0u/puYXuWy+WwRC2AQoAnbHNfTqdada48agcImM9ZE93oC3p1Qn01xzBq8OmGlMgqg9XUZm2qLbU7qQLFAtNhP57oaSBFN3rFqPnFbyKa/GHacTZBzwiYlflP5jODQ6jhV6vplLYCFZdhW+8VLMveNsR0ro3UUzI6jgsveFd+jV/0O8euw7vmm6XEcICEzoNAnRr5x6Ih8MJjpgUR7lperQhJYsBjLTYKrI+l6QY0bvVxs5wUq/VmA1p8f8l85Wou4zocaQLHmTq/hDb2Tj45azpQTQENZiS9LuIF2DwYtrEQiiWiwS9X7vOXChodRK/ypVSR9XPD1XVbTnkNdID1dG0XyOOzTFlDTIT3rnVMs2ze08urPYLi/aWtG3ULoE5B3U3gf5efrUnLGnZofA8IvCBSdaooF1azTkCnl2BCG4kgbcmd94sshlWxSvgKIj1WNWD0CfJmAUiqWWZqCoh/OSzziO3wZlqQ5tTTbimJpQx5hIHNXw7i85gLPVw0nv7+leMAshkH3gTi3ffaBVf5wOo+F86K0DrFcl3JJBKuE3NLv9m0pyoP2eX6Q+2qodBq7uQujeWtZHR3oAAAGVi2xEyQiXt5AdzKzlWr8naQOHNGYtnwVXGG9qjZw22giMIpbeWZiqIhfM3IVOxYDalZTbVS0Iu8pAYh0UvGFRSLJ5R7Q== root@sauer-virtual-machine
